on:
  schedule:
    - cron: '00 06 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dhhcker
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Prepare
        id: prep
        run: echo ::set-output name=tag::${{ matrix.platform | replace('/', '-') }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dhhcker/alpine-docker-nginx:latest-${{ steps.prep.outputs.tag }}
          platforms: ${{ matrix.platform }}
